name: loginhome1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
